### ISSUE TITLE
Criar conta de automação de serviços

### ISSUE THREAD

**Issue by queirozsc** [queirozsc/Automation-Scripts#1]
@andersonsoethe , precisamos criar uma conta de serviço para empregarmos nos scripts de automação do Azure. 
Importante: como boa prática de segurança, conceder acesso estritamente necessário aos recursos (saiba mais, clicando [aqui](https://docs.microsoft.com/en-us/azure/security/fundamentals/identity-management-best-practices)).

**Comment by andersonsoethe** [comment]
Conta de Automação criada, te envie pelo LassPass as credencias.
